spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${{ secrets.RDS_URL }}
    username: ${{ secrets.RDS_USER }}
    password: ${{ secrets.RDS_PASSWD }}

  security:
    oauth2.client:
      registration:
        google:
          client-id: ${{ secrets.GOOGLE_ID }}
          client-secret: ${{ secrets.GOOGLE_SECRET }}
          scope:
            - email
            - profile
        kakao:
          client-id: ${{ secrets.KAKAO_ID }}
          client-secret: ${{ secrets.KAKAO_SECRET }}
          client-authentication-method: POST
          authorization-grant-type: authorization_code
          redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
          scope:
            - profile_nickname
            - account_email
          client-name: Kakao
        naver:
          client-id: ${{ secrets.NAVER_ID }}
          client-secret: ${{ secrets.NAVER_SECRET }}
          client-authentication-method: POST
          authorization-grant-type: authorization_code
          redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
          scope:
            - name
            - email
          client-name: Naver
      provider:
        kakao:
          authorization-uri: https://kauth.kakao.com/oauth/authorize
          token-uri: https://kauth.kakao.com/oauth/token
          user-info-uri: https://kapi.kakao.com/v2/user/me
          user-name-attribute: id
        naver:
          authorization-uri: https://nid.naver.com/oauth2.0/authorize
          token-uri: https://nid.naver.com/oauth2.0/token
          user-info-uri: https://openapi.naver.com/v1/nid/me
          user-name-attribute: response
        
server:
  port: 8080

logging.level:
  org.hibernate.SQL: debug
