name: CI

on:
  push:
    branches: [ main ]
    
  workflow_dispatch:

env:
  S3_BUCKET_NAME: umc-flow
  RESOURCE_PATH: ./src/main/resources/application.yml

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout release
      uses: actions/checkout@v3
    
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: '11'
        distribution: 'temurin'
        
    - name: Set yml file
      uses: microsoft/variable-substitution@v1
      with:
        files: ${{ env.RESOURCE_PATH }}
      env:
        spring.datasource.url: ${{ secrets.RDS_URL }} 
        spring.datasource.username: ${{ secrets.RDS_USER }} 
        spring.datasource.password: ${{ secrets.RDS_PASSWD }}
        spring.security.oauth2.client.registration.google.client-id: ${{ secrets.GOOGLE_ID }}
        spring.security.oauth2.client.registration.google.client-secret: ${{ secrets.GOOGLE_ID }}
        spring.security.oauth2.client.registration.kakao.client-id: ${{ secrets.KAKAO_ID }}
        spring.security.oauth2.client.registration.kakao.client-secret: ${{ secrets.KAKAO_SECRET }}
        spring.security.oauth2.client.registration.naver.client-id: ${{ secrets.NAVER_ID }}
        spring.security.oauth2.client.registration.naver.client-secret: ${{ secrets.NAVER_SECRET }}
        
        
        
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    
    - name: Build with Gradle
      run: ./gradlew clean build
      
    # 디렉토리 생성
    - name: Make Directory
      run: mkdir -p deploy
        
    # Jar 파일 복사
    - name: Copy Jar
      run: cp ./build/libs/*.jar ./deploy
      
    # appspec.yml 파일 복사
    - name: Copy appspec.yml
      run: cp appspec.yml ./deploy

    # script files 복사
    - name: Copy script
      run: cp ./*.sh ./deploy

    - name: Make zip file
      run: zip -r ./flow.zip ./deploy
      shell: bash

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2

    - name: Upload to S3
      run: aws s3 cp --region ap-northeast-2 ./flow.zip s3://umc-flow/
    
    # Deploy
    - name: Deploy
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: aws deploy create-deployment 
        --application-name flow
        --deployment-group-name flow-group
        --file-exists-behavior OVERWRITE 
        --s3-location bucket=umc-flow,bundleType=zip,key=flow.zip 
        --region ap-northeast-2
